{% set name = "html2image" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/html2image-{{ version }}.tar.gz
  sha256: 8d3cf5ee805647d1fb21442137349b3ab0e352b4cac7e4280e2a0f841466e87c

build:
  entry_points:
    - hti = html2image:main
    - html2image = html2image:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - websocket-client 1.*
    - requests

test:
  imports:
    - html2image
  commands:
    - pip check
    - hti --help
    - html2image --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vgalin/html2image
  summary: Package acting as a wrapper around the headless mode of existing web browsers to generate images from URLs and from HTML+CSS strings or files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
